package bo.gaceta.rcb.presentacion.autorizado.servicios;

import javax.xml.namespace.QName;
import javax.xml.ws.*;
import java.net.MalformedURLException;
import java.net.URL;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.11-b150120.1832
 * Generated source version: 2.2
 */
@WebServiceClient(name = "WebServiceRCB", targetNamespace = "http://www.fundempresa.org.bo:10080/wsrcb", wsdlLocation = "http://ws.fundempresa.org.bo:10080/wsrcbdes/servrcb.asmx?WSDL")
public class WebServiceRCB
        extends Service {

    private final static URL WEBSERVICERCB_WSDL_LOCATION;
    private final static WebServiceException WEBSERVICERCB_EXCEPTION;
    private final static QName WEBSERVICERCB_QNAME = new QName("http://www.fundempresa.org.bo:10080/wsrcb", "WebServiceRCB");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://ws.fundempresa.org.bo:10080/wsrcbdes/servrcb.asmx?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WEBSERVICERCB_WSDL_LOCATION = url;
        WEBSERVICERCB_EXCEPTION = e;
    }

    public WebServiceRCB() {
        super(__getWsdlLocation(), WEBSERVICERCB_QNAME);
    }

    public WebServiceRCB(WebServiceFeature... features) {
        super(__getWsdlLocation(), WEBSERVICERCB_QNAME, features);
    }

    public WebServiceRCB(URL wsdlLocation) {
        super(wsdlLocation, WEBSERVICERCB_QNAME);
    }

    public WebServiceRCB(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WEBSERVICERCB_QNAME, features);
    }

    public WebServiceRCB(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WebServiceRCB(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    private static URL __getWsdlLocation() {
        if (WEBSERVICERCB_EXCEPTION != null) {
            throw WEBSERVICERCB_EXCEPTION;
        }
        return WEBSERVICERCB_WSDL_LOCATION;
    }

    /**
     * @return returns WebServiceRCBSoap
     */
    @WebEndpoint(name = "WebServiceRCBSoap")
    public WebServiceRCBSoap getWebServiceRCBSoap() {
        return super.getPort(new QName("http://www.fundempresa.org.bo:10080/wsrcb", "WebServiceRCBSoap"), WebServiceRCBSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns WebServiceRCBSoap
     */
    @WebEndpoint(name = "WebServiceRCBSoap")
    public WebServiceRCBSoap getWebServiceRCBSoap(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fundempresa.org.bo:10080/wsrcb", "WebServiceRCBSoap"), WebServiceRCBSoap.class, features);
    }

    /**
     * @return returns WebServiceRCBSoap
     */
    @WebEndpoint(name = "WebServiceRCBSoap12")
    public WebServiceRCBSoap getWebServiceRCBSoap12() {
        return super.getPort(new QName("http://www.fundempresa.org.bo:10080/wsrcb", "WebServiceRCBSoap12"), WebServiceRCBSoap.class);
    }

    /**
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return returns WebServiceRCBSoap
     */
    @WebEndpoint(name = "WebServiceRCBSoap12")
    public WebServiceRCBSoap getWebServiceRCBSoap12(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.fundempresa.org.bo:10080/wsrcb", "WebServiceRCBSoap12"), WebServiceRCBSoap.class, features);
    }

}
